name: app_script
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  js: ^0.6.7
  json_annotation: ^4.8.1

  google_apps_script:
    path: ../../google_apps_script

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
