name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    environment: dev
    env:
      name: ${{vars.ENV_NAME}}
      app_deployment_id: ${{secrets.APP_DEPLOYMENT_ID}}
      commit_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.1'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build web --release --base-href "/flutter_game_challenges/" --dart-define=ENV_NAME=${{env.name}} --dart-define=APP_DEPLOYMENT_ID=${{env.app_deployment_id}}
      - run: |
          cd build/web
          git init
          git config --global user.email 6490221+adbonnin@users.noreply.github.com
          git config --global user.name "Adrien Bonnin"
          git status
          git remote add origin https://${{env.commit_secret}}@github.com/adbonnin/flutter_game_challenges.git
          git checkout -B gh-pages
          git add --all
          git commit -m ":rocket: Deploy to GitHub pages"
          git push origin gh-pages -f